#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from os import path

def options(opt):
    opt.add_option('-e','--example', help="Informa qual exemplo sera compilado", dest='example_name')

def configure(conf):
    pass
        
def build(bld):
    if(bld.options.example_name):
        bld.program(
            target  = bld.options.example_name,
            source  = path.join('traducoes_exemplo', bld.options.example_name + ".c"),
            use     = ['squirrel-language'])
